### ISSUE TITLE
Peer Error - Wrong Network

### ISSUE THREAD

**Issue by okannako** [celestiaorg/networks#158]
7145da826bbf64f06aa4ad296b850fd697a211cc 

There are warnings that this node is on the wrong network in the logs, it would be better if it was checked and deleted from the list.

https://github.com/celestiaorg/networks/blob/master/mamaki/peers.txt

![celestia](https://user-images.githubusercontent.com/73176377/197368077-031cc7c5-a9a3-4f33-bbe0-d172f824a268.PNG)

**Comment by rootulp** [comment]
Thanks for reporting! Mamaki isn't currently active so closing as unplanned.

**Comment by okannako** [comment]
1 year :)
