### ISSUE TITLE
Switch from FIFO to prioritized mempool

### ISSUE THREAD

**Issue by rootulp** [celestiaorg/networks#161]
## Context

We'd like validators to use the prioritized mempool see https://github.com/celestiaorg/celestia-app/issues/590#issuecomment-1309696579

## Problem

Arabica (and potentially most validators on Mamaki) use the default FIFO mempool. 

## Proposal

We'd like our testnets to be representative of the parameters used on mainnet so we should update the Arabica validator to use the prioritized mempool (i.e. `version: "v1"`). If possible, we should also update any default configuration so that as many validators as possible on Mamaki update to using the prioritized mempool.

**Comment by evan-forbes** [comment]
@rootulp should we move this to a different repo given that the defaults are not picked here? or is this issue indicating something else?

**Comment by rootulp** [comment]
This issue was intended to override the default config on validators for networks like Arabica / Mamaki. If we still want this, which other repo? It doesn't look like https://github.com/celestiaorg/celestia-sre contains configs for validators either.

If we don't want this, we can close this issue and update the default config in celestia-app and wait until the networks upgrade to versions of celestia-app cut with the default changed.

**Comment by evan-forbes** [comment]
imo we can close since we have https://github.com/celestiaorg/celestia-app/pull/1008

what else can we change here?

**Comment by evan-forbes** [comment]
oh I see, we'd close this issue after we update the arabica validator

**Comment by rootulp** [comment]
Yea, I'm okay with closing this given we already merged https://github.com/celestiaorg/celestia-app/pull/1008
Since this issue isn't in a repo we maintain, feel free to re-open and transfer if you want to track it.
