### ISSUE TITLE
doc: Mocha bootstrap-peers is not available on repo

### ISSUE THREAD

**Issue by ningcb** [celestiaorg/networks#174]
https://raw.githubusercontent.com/celestiaorg/networks/master/mocha/bootstrap-peers.txt

This bootstrap-peers.txt does not exist.  None of peers seems alive in https://raw.githubusercontent.com/celestiaorg/networks/master/mocha/peers.txt.

Would you please provide the valid peers to run the consensus full node? 

Thank you.

**Comment by rootulp** [comment]
Hi @ningcb , sorry we didn't get to this sooner. Closing as no longer relevant b/c we're now on the fourth iteration of mocha testnet (`mocha-4`) with peers defined in https://github.com/celestiaorg/networks/blob/master/mocha-4/peers.txt
