### ISSUE TITLE
Format of `peers.txt` changes across testnets

### ISSUE THREAD

**Issue by rootulp** [celestiaorg/networks#350]
## Problem

Some scripts downstream of this repo assume that peers.txt has trailing commas. Some scripts assume no trailing commas. Since this repo doesn't enforce a consistent format, it's not clear what scripts should assume.

https://github.com/celestiaorg/networks/blob/3758740677f29f5ba6a55dfefb89c1e36da413fd/mocha-3/peers.txt#L1-L2 contains trailing commas

https://github.com/celestiaorg/networks/blob/3758740677f29f5ba6a55dfefb89c1e36da413fd/mocha-4/peers.txt#L1-L3 does not.

Consequently, I expect a command in the docs https://docs.celestia.org/nodes/full-consensus-node/#setup-the-p2p-networks to fail because 

> sed -i.bak -e "s/^persistent_peers *=.*/persistent_peers = \"$PERSISTENT_PEERS\"/" $HOME/.celestia-app/config/config.toml

assumes that there are trailing commas.

## Proposal

Describe a format for peers.txt. Enforce it consistently for all peers.txt files. IMO no trailing commas.

**Comment by Bidon15** [comment]
Thanks again for the ping, we will take some homework at @celestiaorg/devops to make sure we have rules set and done in linter so folks are following the rules

**Comment by jcstein** [comment]
note: docs currently have the sed commands set to assume there are no commas in the peers.txt or seeds.txt files

**Comment by jcstein** [comment]
[related comment regarding port formatting in seeds.txt and peers.txt](https://github.com/celestiaorg/networks/pull/522#pullrequestreview-1707070057)
