### ISSUE TITLE
Improve docs on howto join devnet

### ISSUE THREAD

**Issue by liamsi** [celestiaorg/networks#43]
Some feedback gathered from discord (mainly):

The relation between the different binaries is unclear. It already popped up on other channels and again on discord. 
Ideally, there was a brief overview in the readme here and a pointer to more details; these details could be in the celestia-node repo:
> [What is the relation between celesita-app & celestia-node?](https://discord.com/channels/638338779505229824/920642717057421393/923545061336178688)

Newcomers start [following instructions from the top](https://discord.com/channels/638338779505229824/920642717057421393/923895037853564939) and the most relevant parts are only at the very end of the documentation:
> phase1,2,3 is for building up local dev environment. If you want to participate devnet-2, just follow up phaseX.
>> [For new ppl this fact is not clear. A quick mention of this in the beginning of the document will probably save newcomers an hour time.](https://discord.com/channels/638338779505229824/920642717057421393/923934315916722227)

**Comment by aditya-manit** [comment]
I wrote a guide, could be helpful: https://stakeking.notion.site/Join-Celestia-Devnet-2-d4c08af1d0534b3faca7aaa8c1e9266d

**Comment by Bidon15** [comment]
How the further docs will look like
### 1. We need to split the readme.md file to separate md files.
The initial readme will be a high-level overview of how things are interconnected to each other and contain links to other md files 
### 2. It is clear that celestia-appd guide should be a separate md doc
---
What will be changed
1. After installation, Phase X should be standing first (not phase 1/2/3 as it is now) as most of the users are willing to join devnet-2 and not deploy their own network
2. Phase X should be divided into 3 categories 
2.1.  Explanation part 
We need to make it clear that running a non-validator full celestia-appd node is much more preferable as the user doesn't need to put much attention into resolving validator type full nodes and focus on celestia node part later
2.2. Running a non-validator full node (this is more then sufficient to play around later in celestia node part) 
what to add/change:
- how to delegate stake (where to find active validators and etc.) 
- link to a troubleshoot section if the delegation of the stake is not working (we will think about this part later on) 
2.3. Running a validator full node (cart blanche) 
what to add/change: 
- create-validator command
3. Legend + Phase 1/2/3
TBH, I am proposing that we can separate this point into a standalone md file (for the brave ones 😅 )
---
### 3. Separate celestia-node into a separate md doc
Unprepared audience is having a hard time with how to work with celestia-node stuff (Full Nodes/ Light Clients), so we need to separate it to the other readme.md file

### 4. Troubleshooting and F.A.Q should be a 4th file

**Comment by Bidon15** [comment]
Super glad and excited that @yelllowsin is volunteering for the point 2 
I'll be working mainly on point 1 and 3

**Comment by liamsi** [comment]
> how to delegate stake (where to find active validators and etc.)
> link to a troubleshoot section if the delegation of the stake is not working (we will think about this part later on)

This ideally should also be somewhere at the top or very visible at least. As it is a very easy way to interact with the testnet. Same with "Running a non-validator full node".

**Comment by yelllowsin** [comment]
So, I created a new initial Node Setup MD file and sent the PR here: https://github.com/celestiaorg/networks/pull/55
I already tested it in a new VPS, so the instructions should be working. Since we will have a troubleshooting section that is separated, I am still thinking where I should add the extra commands for staking, checking validator, etc. Maybe here via another pull request or in the troubleshooting section.

**Comment by Bidon15** [comment]
I think checking validator should be in the troubleshoot section. Please add another PR 🙏 
Same goes to sending funds from 1 addr to another (if through CLI)

**Comment by Bidon15** [comment]
> Legend + Phase 1/2/3
TBH, I am proposing that we can separate this point into a standalone md file (for the brave ones 😅 )

I think we need to separate this point to a .md doc itself as history has shown that the small minority has been going through creating the own validator network

**Comment by yelllowsin** [comment]
@Bidon15 I have made many improvements to the PR responding many if your comments. Also added an index :) Let me know what you think.
