### ISSUE TITLE
Define `seeds.txt` for arabica-10

### ISSUE THREAD

**Issue by liamsi** [celestiaorg/networks#48]
Either in this or the following testnet we should sping up a few seed nodes (tendermint nodes running in [seed mode](https://docs.tendermint.com/master/spec/p2p/config.html#seed-mode)) and mention those seeds in the seed list. See: https://github.com/celestiaorg/networks/pull/47#discussion_r778057044

**Comment by mindstyle85** [comment]
just raised the PR to add 2 more seeds https://github.com/celestiaorg/networks/pull/53

**Comment by rootulp** [comment]
AFAIK we have 3 supported networks currently:
1. mainnet: does have seeds in https://github.com/celestiaorg/networks/blob/master/celestia/seeds.txt
2. mocha-4: does have seeds in https://github.com/celestiaorg/networks/blob/master/mocha-4/seeds.txt
3. arabica-10: does not contain seeds in https://github.com/celestiaorg/networks/tree/master/arabica-10

**Comment by rootulp** [comment]
I think arabica-10 is deprecated in favor of arabica-11. I wish someone actually added seeds for arabica-10 but IMO this is no longer worth doing.
