### ISSUE TITLE
there a invalid address 

### ISSUE THREAD

**Issue by richard-stakingcabin** [celestiaorg/networks#510]
https://github.com/celestiaorg/networks/blob/3b60f38b3264d951f43b89782991b3e7337651fc/celestia/peers.txt#L27C28-L27C28

when add this peer and start validator show 
'''ERR Error in peer's address err="invalid address (6a50a814bece6ee873467299c9d6d6339055697@162.55.245.228:16656): encoding/hex: odd length hex string" module=p2p
'''

**Comment by richard-stakingcabin** [comment]
98a17a83f8af55157ecb33ea81d4a9d5b9953e0@178.63.76.62:26656 also

**Comment by rootulp** [comment]
Closed by https://github.com/celestiaorg/networks/pull/511
