### ISSUE TITLE
"Celestia Application Installation" link in ReadMe Broken

### ISSUE THREAD

**Issue by totallymystic** [celestiaorg/networks#58]
At the bottom of the page, the "Celestia Application Installation" instructions link is broken. Takes you to a 404 page.

**Comment by Bidon15** [comment]
Thank you @totallymystic  for creating the issue !
ATM, we are in progress with restructuring the guides
Please use this PR as a future ref in installing Celestia Application
https://github.com/celestiaorg/networks/pull/55
